services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0302
      - POSTGRES_DATABASE=lesson_nest
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson_nest
    ports:
      - "6379:6379"